#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "📋 Validating commit message..."

# Validate commit message with commitlint
npx --no -- commitlint --edit "$1"

echo "✅ Commit message validated!"
